Building image pipeline

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -6,164 +6,186 @@ on:
       - feature/*
 
 jobs:
-  SAST:
-      runs-on: ubuntu-latest
-      steps:
-        - name: Checkout del código
-          uses: actions/checkout@v4
-          with:
-            fetch-depth: 0  
+  # SAST:
+  #     runs-on: ubuntu-latest
+  #     steps:
+  #       - name: Checkout del código
+  #         uses: actions/checkout@v4
+  #         with:
+  #           fetch-depth: 0  
 
-        - name: Validando existencia de proyecto en SonarCloud
-          id: validateProjectOnSonar
-          env:
-            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-            PROJECT_NAME: ${{ github.event.repository.name }}
-            ORG_KEY: nixett-devsecops-laboratorio
-          run: |
-            set +e
-            echo "Validando si el proyecto '$PROJECT_NAME' existe en la organización '$ORG_KEY'..."
+  #       - name: Validando existencia de proyecto en SonarCloud
+  #         id: validateProjectOnSonar
+  #         env:
+  #           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  #           PROJECT_NAME: ${{ github.event.repository.name }}
+  #           ORG_KEY: nixett-devsecops-laboratorio
+  #         run: |
+  #           set +e
+  #           echo "Validando si el proyecto '$PROJECT_NAME' existe en la organización '$ORG_KEY'..."
             
-            RESPONSE=$(curl -s -u "${SONAR_TOKEN}:" "https://sonarcloud.io/api/projects/search?organization=$ORG_KEY&q=$PROJECT_NAME")
+  #           RESPONSE=$(curl -s -u "${SONAR_TOKEN}:" "https://sonarcloud.io/api/projects/search?organization=$ORG_KEY&q=$PROJECT_NAME")
             
-            echo "Respuesta de SonarCloud:"
-            echo "$RESPONSE"
+  #           echo "Respuesta de SonarCloud:"
+  #           echo "$RESPONSE"
             
-            PROJECT_KEY="${ORG_KEY}_${PROJECT_NAME}"
-            echo "Buscando projectKey esperado: $PROJECT_KEY"
+  #           PROJECT_KEY="${ORG_KEY}_${PROJECT_NAME}"
+  #           echo "Buscando projectKey esperado: $PROJECT_KEY"
             
-            EXISTE=$(echo "$RESPONSE" | grep -o "\"key\":\"$PROJECT_KEY\"")
+  #           EXISTE=$(echo "$RESPONSE" | grep -o "\"key\":\"$PROJECT_KEY\"")
             
-            if [ -n "$EXISTE" ]; then
-              echo "Proyecto ya existe en SonarCloud"
-              echo "proyectoExiste=1" >> $GITHUB_OUTPUT
-            else
-              echo "Proyecto no encontrado, creando en SonarCloud..."
-              CREATE_RESPONSE=$(curl -s -X POST -u "${SONAR_TOKEN}:" 'https://sonarcloud.io/api/projects/create' \
-                -d "organization=$ORG_KEY" \
-                -d "project=$PROJECT_KEY" \
-                -d "name=$PROJECT_NAME" \
-                -d "visibility=public")
+  #           if [ -n "$EXISTE" ]; then
+  #             echo "Proyecto ya existe en SonarCloud"
+  #             echo "proyectoExiste=1" >> $GITHUB_OUTPUT
+  #           else
+  #             echo "Proyecto no encontrado, creando en SonarCloud..."
+  #             CREATE_RESPONSE=$(curl -s -X POST -u "${SONAR_TOKEN}:" 'https://sonarcloud.io/api/projects/create' \
+  #               -d "organization=$ORG_KEY" \
+  #               -d "project=$PROJECT_KEY" \
+  #               -d "name=$PROJECT_NAME" \
+  #               -d "visibility=public")
 
-              echo "Respuesta de creación: $CREATE_RESPONSE"
+  #             echo "Respuesta de creación: $CREATE_RESPONSE"
 
-              if echo "$CREATE_RESPONSE" | grep -q "\"key\":\"$PROJECT_KEY\""; then
-                echo "Proyecto '$PROJECT_NAME' creado exitosamente."
-                echo "proyectoExiste=0" >> $GITHUB_OUTPUT
-              else
-                echo "Error al crear el proyecto en SonarCloud. Respuesta completa:"
-                echo "$CREATE_RESPONSE"
-                exit 0
-              fi
-            fi
+  #             if echo "$CREATE_RESPONSE" | grep -q "\"key\":\"$PROJECT_KEY\""; then
+  #               echo "Proyecto '$PROJECT_NAME' creado exitosamente."
+  #               echo "proyectoExiste=0" >> $GITHUB_OUTPUT
+  #             else
+  #               echo "Error al crear el proyecto en SonarCloud. Respuesta completa:"
+  #               echo "$CREATE_RESPONSE"
+  #               exit 0
+  #             fi
+  #           fi
 
 
-        - name: Set up JDK 17
-          uses: actions/setup-java@v4
-          with:
-            java-version: '17'
-            distribution: 'temurin'
+  #       - name: Set up JDK 17
+  #         uses: actions/setup-java@v4
+  #         with:
+  #           java-version: '17'
+  #           distribution: 'temurin'
 
-        - name: SonarCloud Scan
-          uses: sonarsource/sonarcloud-github-action@v2
-          env:
-            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          with:
-            args: >
-              -Dsonar.organization=nixett-devsecops-laboratorio
-              -Dsonar.projectKey=nixett-devsecops-laboratorio_devsecops-laboratorio
-              -Dsonar.sources=src,functions
-              -Dsonar.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts
-              -Dsonar.typescript.tsconfigPath=tsconfig.json
-              -Dsonar.host.url=https://sonarcloud.io
-              -Dsonar.branch.name=${{ github.ref_name }}
-              -X
+  #       - name: SonarCloud Scan
+  #         uses: sonarsource/sonarcloud-github-action@v2
+  #         env:
+  #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  #         with:
+  #           args: >
+  #             -Dsonar.organization=nixett-devsecops-laboratorio
+  #             -Dsonar.projectKey=nixett-devsecops-laboratorio_devsecops-laboratorio
+  #             -Dsonar.sources=src,functions
+  #             -Dsonar.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts
+  #             -Dsonar.typescript.tsconfigPath=tsconfig.json
+  #             -Dsonar.host.url=https://sonarcloud.io
+  #             -Dsonar.branch.name=${{ github.ref_name }}
+  #             -X
 
-        - name: Mostrar archivos en src
-          run: |
-            echo "=== Archivos en src ==="
-            ls -R src
+  #       - name: Mostrar archivos en src
+  #         run: |
+  #           echo "=== Archivos en src ==="
+  #           ls -R src
 
-        - name: Validando vulnerabilidades y hotspots en SonarCloud
-          env:
-            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-            PROJECT_KEY: nixett-devsecops-laboratorio_devsecops-laboratorio
-            BRANCH: ${{ github.ref_name }}
-          run: |
-            echo "Validando vulnerabilidades y hotspots en SonarCloud para $PROJECT_KEY ($BRANCH)..."
+  #       - name: Validando vulnerabilidades y hotspots en SonarCloud
+  #         env:
+  #           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  #           PROJECT_KEY: nixett-devsecops-laboratorio_devsecops-laboratorio
+  #           BRANCH: ${{ github.ref_name }}
+  #         run: |
+  #           echo "Validando vulnerabilidades y hotspots en SonarCloud para $PROJECT_KEY ($BRANCH)..."
 
-            RESPONSE_VULN=$(curl -s -u "${SONAR_TOKEN}:" \
-              "https://sonarcloud.io/api/issues/search?branch=${BRANCH}&componentKeys=${PROJECT_KEY}&types=VULNERABILITY")
-            TOTAL_VULN=$(echo "$RESPONSE_VULN" | jq '.total // 0')
+  #           RESPONSE_VULN=$(curl -s -u "${SONAR_TOKEN}:" \
+  #             "https://sonarcloud.io/api/issues/search?branch=${BRANCH}&componentKeys=${PROJECT_KEY}&types=VULNERABILITY")
+  #           TOTAL_VULN=$(echo "$RESPONSE_VULN" | jq '.total // 0')
 
-            RESPONSE_HOTSPOT=$(curl -s -u "${SONAR_TOKEN}:" \
-              "https://sonarcloud.io/api/hotspots/search?projectKey=${PROJECT_KEY}&branch=${BRANCH}")
-            TOTAL_HOTSPOT=$(echo "$RESPONSE_HOTSPOT" | jq '.paging.total // 0')
+  #           RESPONSE_HOTSPOT=$(curl -s -u "${SONAR_TOKEN}:" \
+  #             "https://sonarcloud.io/api/hotspots/search?projectKey=${PROJECT_KEY}&branch=${BRANCH}")
+  #           TOTAL_HOTSPOT=$(echo "$RESPONSE_HOTSPOT" | jq '.paging.total // 0')
 
-            echo "Vulnerabilidades detectadas: $TOTAL_VULN"
-            echo "Hotspots detectados: $TOTAL_HOTSPOT"
+  #           echo "Vulnerabilidades detectadas: $TOTAL_VULN"
+  #           echo "Hotspots detectados: $TOTAL_HOTSPOT"
 
-            TOTAL=$((TOTAL_VULN + TOTAL_HOTSPOT))
-            echo "Total combinado: $TOTAL"
+  #           TOTAL=$((TOTAL_VULN + TOTAL_HOTSPOT))
+  #           echo "Total combinado: $TOTAL"
 
-            if [ "$TOTAL" -gt 0 ]; then
-              echo "Se detectaron vulnerabilidades o hotspots de seguridad en SonarCloud."
-              # exit 1
-            else
-              echo "No se encontraron vulnerabilidades ni hotspots críticos."
-            fi
+  #           if [ "$TOTAL" -gt 0 ]; then
+  #             echo "Se detectaron vulnerabilidades o hotspots de seguridad en SonarCloud."
+  #             # exit 1
+  #           else
+  #             echo "No se encontraron vulnerabilidades ni hotspots críticos."
+  #           fi
 
-  SCA:
-    needs: SAST
+  # SCA:
+  #   needs: SAST
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout del código
+  #       uses: actions/checkout@v4
+
+  #     - name: Configurar Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 18
+
+  #     - name: Instalar dependencias
+  #       run: npm install
+
+  #     - name: Ejecutar OWASP Dependency-Check
+  #       uses: dependency-check/Dependency-Check_Action@1.1.0
+  #       with:
+  #         project: '${{ github.event.repository.name }}'
+  #         path: '.'
+  #         format: 'ALL'
+  #         args: >
+  #           --enableRetired
+  #           --failOnCVSS 4
+
+  #     - name: Analizar vulnerabilidades detectadas (CVSS >= 4)
+  #       run: |
+  #         echo "Analizando vulnerabilidades del reporte JSON..."
+
+  #         REPORT_JSON="reports/dependency-check-report.json"
+
+  #         if [ ! -f "$REPORT_JSON" ]; then
+  #           echo "No se encontró el reporte JSON en $REPORT_JSON"
+  #           exit 1
+  #         fi
+
+  #         COUNT=$(jq '[.dependencies[].vulnerabilities[]? | select(.cvssScore >= 4)] | length' "$REPORT_JSON")
+
+  #         echo "Vulnerabilidades con CVSS >= 4 detectadas: $COUNT"
+
+  #         if [ "$COUNT" -gt 0 ]; then
+  #           echo "Se encontraron vulnerabilidades medias, altas o críticas. Quebrando el pipeline."
+  #           exit 1
+  #         else
+  #           echo "No se encontraron vulnerabilidades medias, altas o críticas."
+  #         fi
+
+  #     - name: Subir reporte de análisis SCA
+  #       uses: actions/upload-artifact@v4
+  #       if: always()
+  #       with:
+  #         name: Dependency-Check-Report
+  #         path: reports
+
+  DockerBuild:
+    # needs: SCA
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout del código
-        uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-      - name: Configurar Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 18
-
-      - name: Instalar dependencias
-        run: npm install
-
-      - name: Ejecutar OWASP Dependency-Check
-        uses: dependency-check/Dependency-Check_Action@1.1.0
-        with:
-          project: '${{ github.event.repository.name }}'
-          path: '.'
-          format: 'ALL'
-          args: >
-            --enableRetired
-            --failOnCVSS 4
-
-      - name: Analizar vulnerabilidades detectadas (CVSS >= 4)
+      - name: Build Docker Image
         run: |
-          echo "Analizando vulnerabilidades del reporte JSON..."
+          docker build \
+            --tag ${{ secrets.DOCKER_USER }}/devsecops-laboratorio:${{ github.run_number }} \
+            --tag ${{ secrets.DOCKER_USER }}/devsecops-laboratorio:latest .
 
-          REPORT_JSON="reports/dependency-check-report.json"
-
-          if [ ! -f "$REPORT_JSON" ]; then
-            echo "No se encontró el reporte JSON en $REPORT_JSON"
-            exit 1
-          fi
-
-          COUNT=$(jq '[.dependencies[].vulnerabilities[]? | select(.cvssScore >= 4)] | length' "$REPORT_JSON")
-
-          echo "Vulnerabilidades con CVSS >= 4 detectadas: $COUNT"
-
-          if [ "$COUNT" -gt 0 ]; then
-            echo "Se encontraron vulnerabilidades medias, altas o críticas. Quebrando el pipeline."
-            exit 1
-          else
-            echo "No se encontraron vulnerabilidades medias, altas o críticas."
-          fi
-
-      - name: Subir reporte de análisis SCA
-        uses: actions/upload-artifact@v4
-        if: always()
+      - name: Login to DockerHub
+        uses: docker/login-action@v3
         with:
-          name: Dependency-Check-Report
-          path: reports
+          username: ${{ secrets.DOCKER_USER }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Push to DockerHub
+        run: docker push ${{ secrets.DOCKER_USER }}/devsecops-laboratorio:latest
